import { Box, Container, Heading } from '@chakra-ui/layout';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { Personas } from '../components';
import styles from '../styles/Home.module.css';
import { getList } from './api/sheets';

export default function Home({ infoData }) {
  const [data, setData] = useState([]);

  useEffect(() => {
    setData(infoData);
  }, []);

  console.log(data);

  return (
    <Container maxW="1400px" p={5}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading>Google sheets database</Heading>
      <Box>
        {data.map((cat) => (
          <Personas
            key={cat.id}
            name={cat.name}
            age={cat.age}
            country={cat.country}
          />
        ))}
      </Box>
    </Container>
  );
}

export async function getStaticProps(context) {
  const data = await getList();
  const allData = await JSON.stringify(data);
  const info = JSON.parse(allData);

  return {
    props: {
      infoData: info.slice(1, info.length),
    },
    revalidate: 10, // segundos
  };
}
